<?php


namespace Project\AdminBundle\Form\CustomExtensions;


use Project\Utils\Core\Php\SystemSettings;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\PropertyAccess\PropertyAccess;


class FormTypeExtension extends AbstractTypeExtension
{

    private $container;
    public function __construct(ContainerInterface $container)
    {
        $this->container = $container;
    }



    public function configureOptions(OptionsResolver $resolver)
    {
        // makes it legal for FileType fields to have an image_property option
        $resolver->setDefined(['full_row']);
        $resolver->setDefaults(
            array(
                'container' => $this->container
            )
        );

//        $resolver->setDefined(['image_dir_parameter']);
//        $resolver->setDefined(['width']);
//        $resolver->setDefined(['height']);
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
//        parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub

        if(@$options["full_row"]){
            $view->vars['full_row'] = @$options["full_row"];

        }
    }

    /**
     * {@inheritdoc}
     */
    public function getExtendedType()
    {
        return 'Symfony\Component\Form\Extension\Core\Type\FormType';
    }

}
